version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-container
    networks:
      - localnetwork
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: rootname
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: occurrences-images

    volumes:
      - 'minio_data:/data'
    command: server /data --console-address ":9001"
  postgres:
    container_name: postgresDB
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    networks:
      - localnetwork

  application-app:
    container_name: "carbigdata-service"
    depends_on:
      - minio
      - postgres
    image: service-image:latest
    networks:
      - localnetwork
    build: ../ms
    ports:
      - 8080:8080

networks:
  localnetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local